HOST = '127.0.0.1'  # Localhost
PORT = 8080  # Port for the server
BUFFER_SIZE = 1024  # Buffer size for communication
ENCODE = 'utf-8'  # Encoding for the communication
TIME_STAMP_FORMAT = "%Y-%m-%d %H:%M:%S"  # Time stamp format for messages
CLIENT_CHAT_TABLE = "client_chats"  # Table name for client chat messages
CLIENT_PRIVATE_KEY = "private_key.pem"  # Table name for client private key
CLIENT_PUBLIC_KEY = "public_key.pem"  # Table name for client public key
SERVER_PUBLIC_KEY = "server_public_key.pem"  # Table name for server public key