from enum import Enum


class MessageType(Enum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
    OUTGOING_MESSAGE_SUCCESS = "OUTGOING_MESSAGE_SUCCESS"
    INCOMING_MESSAGE = "INCOMING_MESSAGE"
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"