from enum import Enum

class MessageType(Enum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN = "LOGIN"
    REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
    REGISTER = "REGISTER"
    OUTGOING_CHAT_MESSAGE_SUCCESS = "OUTGOING_CHAT_MESSAGE_SUCCESS"
    OUTGOING_CHAT_MESSAGE = "OUTGOING_CHAT_MESSAGE"
    INCOMING_CHAT_MESSAGE = "INCOMING_CHAT_MESSAGE"
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"